using System;
using CSharpNumerics.Numerics.Objects;

namespace CSharpNumerics.Engines.Game.Rocket;

/// <summary>
/// Models thrust vector control (TVC) via engine gimbal.
/// Converts gimbal deflection commands into torques about the vehicle CG,
/// with actuator rate and angle limits.
/// </summary>
public class ThrustVectorControl
{
    /// <summary>Maximum gimbal deflection angle (radians). Default ±5°.</summary>
    public double MaxGimbalAngle { get; set; } = 5.0 * Math.PI / 180.0;

    /// <summary>Maximum gimbal slew rate (rad/s). Default 10°/s.</summary>
    public double MaxGimbalRate { get; set; } = 10.0 * Math.PI / 180.0;

    /// <summary>Distance from CG to gimbal point along body X-axis (meters). Default 20 m.</summary>
    public double MomentArm { get; set; } = 20.0;

    /// <summary>Current gimbal deflection in pitch (body Y torque) (radians).</summary>
    public double GimbalPitch { get; private set; }

    /// <summary>Current gimbal deflection in yaw (body Z torque) (radians).</summary>
    public double GimbalYaw { get; private set; }

    /// <summary>
    /// Commands a gimbal deflection and applies rate/angle limiting.
    /// </summary>
    /// <param name="commandedPitch">Desired pitch gimbal angle (radians).</param>
    /// <param name="commandedYaw">Desired yaw gimbal angle (radians).</param>
    /// <param name="dt">Time step (seconds).</param>
    public void Command(double commandedPitch, double commandedYaw, double dt)
    {
        // Rate limit
        double pitchError = Clamp(commandedPitch, -MaxGimbalAngle, MaxGimbalAngle) - GimbalPitch;
        double yawError = Clamp(commandedYaw, -MaxGimbalAngle, MaxGimbalAngle) - GimbalYaw;

        double maxDelta = MaxGimbalRate * dt;

        GimbalPitch += Clamp(pitchError, -maxDelta, maxDelta);
        GimbalYaw += Clamp(yawError, -maxDelta, maxDelta);

        // Angle limit
        GimbalPitch = Clamp(GimbalPitch, -MaxGimbalAngle, MaxGimbalAngle);
        GimbalYaw = Clamp(GimbalYaw, -MaxGimbalAngle, MaxGimbalAngle);
    }

    /// <summary>
    /// Computes the torque generated by the current gimbal deflection given thrust magnitude.
    /// Torque = thrust × moment arm × sin(gimbal angle), in body frame.
    /// </summary>
    /// <param name="thrustMagnitude">Current total thrust (N).</param>
    /// <returns>Torque vector in body frame (N·m).</returns>
    public Vector ComputeTorque(double thrustMagnitude)
    {
        // Gimbal pitch creates torque about body Y axis
        // Gimbal yaw creates torque about body Z axis
        double torqueY = thrustMagnitude * MomentArm * Math.Sin(GimbalPitch);
        double torqueZ = thrustMagnitude * MomentArm * Math.Sin(GimbalYaw);

        return new Vector(0, torqueY, torqueZ);
    }

    /// <summary>
    /// Given a desired torque vector, computes and applies the required gimbal angles.
    /// </summary>
    /// <param name="desiredTorque">Desired torque in body frame (N·m).</param>
    /// <param name="thrustMagnitude">Current thrust magnitude (N).</param>
    /// <param name="dt">Time step (seconds).</param>
    public void CommandFromTorque(Vector desiredTorque, double thrustMagnitude, double dt)
    {
        if (thrustMagnitude < 1.0)
        {
            Command(0, 0, dt);
            return;
        }

        double effectiveArm = thrustMagnitude * MomentArm;
        double cmdPitch = Math.Asin(Clamp(desiredTorque.y / effectiveArm, -1.0, 1.0));
        double cmdYaw = Math.Asin(Clamp(desiredTorque.z / effectiveArm, -1.0, 1.0));

        Command(cmdPitch, cmdYaw, dt);
    }

    /// <summary>Resets gimbal to center position.</summary>
    public void Reset()
    {
        GimbalPitch = 0;
        GimbalYaw = 0;
    }

    private static double Clamp(double value, double min, double max)
    {
        if (value < min) return min;
        if (value > max) return max;
        return value;
    }
}
